In [4]:
# Q1 solution
'''
line 3 will produce an error # C = A * B

'''

# correction of code
import numpy as np
A = np.array([1, 2, 3, 4])
B = np.array([5, 6, 7])

C = A[:len(B)] * B
total_sum = np.sum(C)
print(total_sum)

38


In [11]:
# Q2 Solution
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)
B = np.array([1, 0, -1], dtype=np.int32)

C = A * B
print(C)
print(C.shape)
# There is no issue in the broadcasting 

D = C.reshape(3, 2, 1)
print(D)
print(D.shape)



E = D + 3.5

print(E)
print(E.shape)

[[ 1.  0. -3.]
 [ 4.  0. -6.]]
(2, 3)
[[[ 1.]
  [ 0.]]

 [[-3.]
  [ 4.]]

 [[ 0.]
  [-6.]]]
(3, 2, 1)
[[[ 4.5]
  [ 3.5]]

 [[ 0.5]
  [ 7.5]]

 [[ 3.5]
  [-2.5]]]
(3, 2, 1)


In [7]:
# Q3 solution
import numpy as np

A = np.arange(1, 101)
matrix_A = A.reshape(10, 10) 
matrix_A[matrix_A % 3 == 0] = -3 
matrix_A = matrix_A[::-1]
last_two_columns = matrix_A[:, -2:]

print(last_two_columns)


[[ -3 100]
 [ 89  -3]
 [ 79  80]
 [ -3  70]
 [ 59  -3]
 [ 49  50]
 [ -3  40]
 [ 29  -3]
 [ 19  20]
 [ -3  10]]
