In [1]:
# Q1 Solution
'''
    10^2 != 100 since ^ is a bitwise XOR operator
    10 -> 1010
    2 -> 10
    -----------
    8 -> 1000
'''
print(10^2)


8


In [ ]:
# Q2 Solution
'''  XOR 
    True ^ True -> False
    True ^ False -> True
    False ^ True -> True
    False ^ False -> False
'''
#  two ways of constructing xor using existing operators


In [9]:
# Q3 Solution
from math import copysign

def sign(a):
    if(a<0):
        return copysign(1,a)
    else:
        return copysign(1,a)

print(int(sign(10)))
print(int(sign(0))) 
print(int(sign(-10)))   
    

1
1
-1


In [10]:
# Q4 Solution : What does the code below print?
pset_time = 15 
sleep_time = 8 
print(sleep_time > pset_time) 
derive = True 
drink = False 
both = drink and derive 
print(both)

False
False


In [13]:
# Q5 Solution : What is the value of L3 after you execute all the operations in the code below?
L1 = ['re']
L2 = ['ga']
L3 = ['sa']
L4 = L1 + L2
print(L4)
L3.extend(L4)
print(L3)
L3.sort()
print(L3)
del(L3[0])
print(L3)
L3.append(['ma','dha'])
print(L3)

['re', 'ga']
['sa', 're', 'ga']
['ga', 're', 'sa']
['re', 'sa']
['re', 'sa', ['ma', 'dha']]


In [27]:
# Q6 Solution : Find bug in the loop without coding then write the correct code.
''' 
n = 10
i = 10
while i > 0:
    print i
    if i % 2 == 0:
        i = i / 2
    else:
        i = i + 1
'''
# Bugs: print i & infinite loop

# Corrected Code
n = 10
i = 10
while(i>0):
    print("i = %d | n = %d"%(i,n))
    if(n % 2 == 0):
        i = i // 2
    else:
        i = i + 1    

i = 10 | n = 10
i = 5 | n = 10
i = 2 | n = 10
i = 1 | n = 10


In [37]:
# Q7 Solution
import numpy as np

def sort_array(A):
    

A = np.random.rand(4,5)
print(A)

[[0.71304801 0.45373124 0.985069   0.11285059 0.10916926]
 [0.60015859 0.85180133 0.77032906 0.40991256 0.81014067]
 [0.09614872 0.44895379 0.50701432 0.36675715 0.88810678]
 [0.04834444 0.00598675 0.95906216 0.81080452 0.67653522]]


In [5]:
# Q8 Solution
''' 
Write programs to test the following NumPy broadcasting rule: 
When operating on two arrays, NumPy compares their shapes element-wise. It starts with 
the trailing or rightmost dimension and works its way left. Two dimensions are compatible 
when they are equal or one of them is 1. 
'''

import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[9,8,7]])
print(a+b)
# a(2,3) & b(1,3)

a = np.array([[1,2,3]])
b = np.array([[10],[9],[15]])
print(a+b)
# a(1,3) & b(3,1)

a = np.array([[1],[2],[3]])
b = np.array([[4,1],[5,2],[6,3]])
print(a+b)
# a(3,1) & b(3,2)

[[10 10 10]
 [13 13 13]]
[[11 12 13]
 [10 11 12]
 [16 17 18]]
[[5 2]
 [7 4]
 [9 6]]


In [8]:
# Q9 Solution
''' 
Make an array with dtype = uint8 and elements of your choosing. Keep adding to it until 
(one of) the items go over 255. What do you observe? Hint: make an array, and just add a 
constant to it. The constant will be added to all the items of the array element-wise. 
'''
A = np.array([10,20,30,40,50,100], dtype=np.uint8) # range of uint8 [0, 255]
A = A + 100
print(A)
A = A + 100
print(A)

[110 120 130 140 150 200]
[210 220 230 240 250  44]
